[project]
name = "braglog"
version = "0.1.0"
description = ""

readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyobjc (>=11.0,<12.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
